apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.name}}
spec:
  capacity:
    storage: {{.size}}Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: /pvs/{{.name}}
  persistentVolumeReclaimPolicy: Recycle
